name: Simple Docker Build

on:
  push:
    branches: [ main ]
  workflow_dispatch:  # Allow manual triggering

env:
  REGISTRY: ghcr.io

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Debug - Show environment
      run: |
        echo "Actor: ${{ github.actor }}"
        echo "Repository: ${{ github.repository }}"
        echo "Repository (lowercase): ${GITHUB_REPOSITORY,,}"
        echo "Registry: ${{ env.REGISTRY }}"

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build Docker image (no push)
      uses: docker/build-push-action@v5
      with:
        context: .
        platforms: linux/amd64
        push: false
        tags: ${{ env.REGISTRY }}/${{ github.repository }}:test

    - name: Test push to registry
      run: |
        IMAGE_NAME="${{ env.REGISTRY }}/${{ github.repository }}:test"
        echo "Attempting to push: $IMAGE_NAME"
        docker buildx build --platform linux/amd64 --push -t "$IMAGE_NAME" . 